---
title: "Weighted Cumulative Exposure : Signal detection"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Weighted Cumulative Exposure : Signal detection}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

<!-- WCE.Rmd.orig produces WCE.Rmd; please edit WCE.Rmd.orig and run vignettes/precompile.R -->




The Weighted Cumulative Exposure (WCE) model[^wce] extends the Cox proportional hazards model to time-varying exposures whose effect on the hazard depends not only on the current exposure level but also on how it has evolved over time. It estimates a weight function that captures how the influence of past exposure on the hazard changes with the time elapsed since it occurred, so that the cumulative effect at any given time is a weighted sum of the exposure history up to that point.


Let's make an example with `drugdata` dataset from WCE package. Before load `survivalGPU`, use your virtual python environment (see `vignette("python_connect")`).


``` r
library(reticulate)
use_virtualenv(virtualenv = "survivalGPU")
```



```
#>   Id Event Start Stop sex age dose
#> 1  1     0     0    1   1  40    0
#> 2  1     0     1    2   1  40    0
#> 3  1     0     2    3   1  40    0
#> 4  1     0     3    4   1  40    0
#> 5  1     0     4    5   1  40    0
#> 6  1     0     5    6   1  40    0
```

Check if CUDA is detected :


``` r
use_cuda()
#> [1] FALSE
```

By default, functions run with GPU if detected. Then we specify the number of bootstrap, and consequently the batchsize argument, according to CUDA drivers detection.


``` r
if (use_cuda()) {
  n_bootstrap <- 1000
  batchsize <- 200
} else {
  n_bootstrap <- 50
  batchsize <- 10
}
```


WCE allows modeling the cumulative effects of time-varying exposures, weighted according to their relative proximity in time and represented by time-dependent covariates. Currently, the weight function is estimated by the Cox proportional hazards model. To build a model, you can use the `wceGPU` function in the same way as the `WCE::WCE` function from WCE package.


``` r
wce_gpu_bootstrap <- wceGPU(data = drugdata, nknots = 1, cutoff = 90, id = "Id",
                            event = "Event", start = "Start", stop = "Stop",
                            expos = "dose", covariates = c("age", "sex"),
                            constrained = FALSE, aic = FALSE, confint = 0.95,
                            nbootstraps = n_bootstrap, batchsize = batchsize)
```

In the summary, there are estimated coefficients for the covariates with his confidence interval, calculated with var-covariance matrix, and information to see the significance of the covariates. It's also possible to have confidence interval with bootstrap.


``` r
summary(wce_gpu_bootstrap)
```

The risk function can be plot, and if you added bootstrap, confidence band intervals will be visible.


``` r
plot(wce_gpu_bootstrap)
```


## Hazards Ratios

`HR()` computes the hazard ratio between two exposure profiles — for example a constantly exposed patient versus an unexposed one — using the estimated WCE weight function. If the model was fit with bootstrap resampling (`nbootstraps > 0`), it also reports a bootstrap confidence interval for that hazard ratio.


``` r
# cutoff at 90 in the WCE model
exposed   <- rep(1, 90)
unexposed <- rep(0, 90)

HR(wce_gpu_bootstrap, exposed, unexposed)
```


## References

[^wce]: Sylvestre MP, Abrahamowicz M. Flexible modeling of the cumulative effects of time-dependent exposures on the hazard. Stat Med. 2009 Nov 30;28(27):3437-53.
