# Install survivalGPU from source, run the tests and upload the coverage to Codecov
# this workflow is triggered on pull request  and push to main branch
name: Python tests

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  install_and_run_tests:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      # R is needed to install rpy2 and run the tests against
      # the reference R package survival
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          # Currently, rpy2 is broken for R 4.5.0.
          # See https://github.com/rpy2/rpy2/issues/1164
          r-version: 4.4.3
          use-public-rspm: true

      - name: Install R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check
          working-directory: "R/"

      - name: Install package (with dependencies for tests)
        run: |
          pip install --upgrade pip
          pip install -e .[test]
          export LD_LIBRARY_PATH=$(python -m rpy2.situation LD_LIBRARY_PATH):${LD_LIBRARY_PATH}

      - name: Test
        run: |
          pytest

      - name: Upload coverage to Codecov
        if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.12'
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: false
          files: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
